### ISSUE TITLE
Shape doesn't match!

### ISSUE THREAD

**Issue by lancexiang** [andreped/PLS-Net#1]
When i test the main model pls_net with a random shape: (140, 140, 140)，then occurs a eroors corresponding to shape doesn't match? The network support arbitrary shape?

**Comment by andreped** [comment]
No, the network does not support arbitrary shape. There are several reasons to why that is, for instance in terms of different operations and kernels used, but especially in terms of skip connection and stuff related to that. 

You will run into issues if you for instance use odd-numbered shapes, as you will have problems upsampling to produce the correct shape in the decoder, and there will likely also be a mismatch between shapes at different levels, coming from the bottom of the decoder and from the skip connection. There are ways to make this even more generic, to handle these types of events better, but this wasn't something we dedicated time to do. I would also say that, with extra caution, it is not necessary.

I would recommend working with shapes of power of 2, or at least shapes that are divisible by 2 sufficiently many times. There could also be added support for arbitrary depth as well, but since we made this implementation for a paper (with fixed architecture), some of the solution is hard-coded, sadly.

**Comment by lancexiang** [comment]
Okay, Thanks for your quick reply. Because i didn't see the fixed size instead of resample to (1.0x1.0x1.0) in the paper, it's supposed to handle arbitrary shape. Little problem, fine~

**Comment by andreped** [comment]
The architecture itself can likely support arbitrary shape (at least in a logical range), but our implementation is not a perfect generalization. If you wish to make the architecture deeper or adjust some components, you would have to change some of the code yourself, but since it is pytorch that should be straightforward. As you were using 140^3 volumes, I would perhaps use 128^3 volumes instead.

Information on which input shape we used can be found in Table 2, Section 3.3.2 of our paper: https://arxiv.org/pdf/2010.07002.pdf

If you run into any issues adapting the code to your problem, let me know if I could be of any assistance :)

For the same task, we also proposed a more complex architecture to further improve F1 and segmentation (perhaps that would also be of interest to you?): https://arxiv.org/abs/2101.07715

The same architecture(s) were also tested on lymph node segmentation from CTs (https://arxiv.org/abs/2102.06515). The source code for these architectures can be found [here](https://github.com/dbouget/mri_brain_tumor_segmentation ).
